name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build kvault and test kvault (Android)
        run: ./gradlew build test -x iosTest
      - name: Build hostapp and test kvault (iOS)
        run: |
          cd hostapp
          sudo xcode-select -switch /Applications/Xcode_11.6_beta.app
          xcodebuild clean test -project HostApp.xcodeproj -scheme HostApp -destination "platform=iOS Simulator,OS=13.6,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Upload test result
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: kvault/build/reports/
